// Related words Ask Aide treats as meaning the same thing when searching for
// matching guides, so a caregiver typing "shower" also finds "bathing" content.
export const querySynonyms: Record<string, string[]> = {
  shower: ['bath', 'bathing', 'bathe', 'hygiene', 'wash'],
  showers: ['bath', 'bathing', 'bathe', 'hygiene', 'wash'],
  bathe: ['bath', 'bathing', 'shower', 'hygiene', 'wash'],
  bathing: ['bath', 'bathe', 'shower', 'hygiene', 'wash'],
  wash: ['bath', 'bathing', 'shower', 'hygiene'],
  eat: ['eating', 'food', 'nutrition', 'meal', 'appetite'],
  eating: ['eat', 'food', 'nutrition', 'meal', 'appetite'],
  food: ['eat', 'eating', 'nutrition', 'meal', 'appetite'],
  restroom: ['bathroom', 'toilet', 'incontinence'],
  toilet: ['bathroom', 'incontinence', 'toileting'],
  lost: ['wandering', 'safety'],
  leave: ['wandering', 'exit', 'safety'],
  leaving: ['wandering', 'exit', 'safety'],
  fall: ['falls', 'falling', 'trip', 'balance', 'mobility', 'safety'],
  falls: ['fall', 'falling', 'trip', 'balance', 'mobility', 'safety'],
  falling: ['falls', 'fall', 'trip', 'balance', 'mobility', 'safety'],
  head: ['falls', 'injury', 'safety'],
  meds: ['medication', 'medicine', 'pills', 'routine', 'health'],
  pills: ['medication', 'medicine', 'meds', 'routine', 'health'],
  medicine: ['medication', 'meds', 'pills', 'routine', 'health'],
  uti: ['infection', 'sudden', 'confusion', 'delirium', 'medical'],
  infection: ['uti', 'sudden', 'confusion', 'delirium', 'medical'],
  sudden: ['infection', 'uti', 'delirium', 'medical'],
  home: ['house', 'familiar', 'reassurance', 'routine'],
  follow: ['shadowing', 'anxiety', 'reassurance', 'behavior'],
  follows: ['shadowing', 'anxiety', 'reassurance', 'behavior'],
  following: ['shadowing', 'anxiety', 'reassurance', 'behavior'],
  clingy: ['shadowing', 'anxiety', 'reassurance', 'behavior'],
  panic: ['anxiety', 'fear', 'reassurance', 'behavior'],
  panics: ['anxiety', 'fear', 'reassurance', 'behavior'],
  hide: ['rummaging', 'lost', 'accusations', 'paranoia'],
  hiding: ['rummaging', 'lost', 'accusations', 'paranoia'],
  rummage: ['rummaging', 'searching', 'behavior'],
  stove: ['kitchen', 'cooking', 'home', 'safety'],
  kitchen: ['stove', 'cooking', 'home', 'safety'],
  scam: ['scams', 'money', 'financial', 'protection'],
  scams: ['scam', 'money', 'financial', 'protection'],
  money: ['financial', 'scams', 'legal', 'protection'],
  hospice: ['comfort', 'late', 'stage', 'care', 'planning'],
  respite: ['breaks', 'support', 'caregiver', 'help'],
  facility: ['care', 'home', 'assisted', 'living', 'transition'],
  nursing: ['care', 'home', 'facility', 'transition'],
  angry: ['aggression', 'behavior', 'agitation'],
  scared: ['anxiety', 'fear', 'behavior'],
  confused: ['confusion', 'memory', 'communication'],
};
